"""models enhancement

Revision ID: 348689f3d004
Revises: 144bfcef40e4
Create Date: 2023-11-23 15:50:43.616917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '348689f3d004'
down_revision: Union[str, None] = '144bfcef40e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'status',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('events', 'notes',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'notes',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('contracts', 'status',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
